services:
  - type: web
    name: VJ-Filter-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PORT
        value: 8080